//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoGISBot.Telegram {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoGISBot.Telegram.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No addresses found by provided search prompt..
        /// </summary>
        internal static string AddressesNotFound {
            get {
                return ResourceManager.GetString("AddressesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Addresses from &lt;a href=&quot;{2}&quot;&gt;{1}&lt;/a&gt; according to search prompt &quot;&lt;b&gt;{0}&lt;/b&gt;&quot;:.
        /// </summary>
        internal static string AddressResultsStart {
            get {
                return ResourceManager.GetString("AddressResultsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No cadastre numbers found by your search prompt..
        /// </summary>
        internal static string CadastreNotFound {
            get {
                return ResourceManager.GetString("CadastreNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cadastre numbers from &lt;a href=&quot;{2}&quot;&gt;{1}&lt;/a&gt; according to search prompt &quot;{0}&quot;:.
        /// </summary>
        internal static string CadastreResultsStart {
            get {
                return ResourceManager.GetString("CadastreResultsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Updated catalog information..
        /// </summary>
        internal static string CatalogFetched {
            get {
                return ResourceManager.GetString("CatalogFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command {0} not found..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Description.
        /// </summary>
        internal static string MapDescription {
            get {
                return ResourceManager.GetString("MapDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maps from &lt;a href=&quot;{2}&quot;&gt;{1}&lt;/a&gt; according to search prompt &quot;{0}&quot;:.
        /// </summary>
        internal static string MapResultsStart {
            get {
                return ResourceManager.GetString("MapResultsStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See &lt;a href=&quot;{1}&quot;&gt;{0}&lt;/a&gt; in &lt;a href=&quot;{3}&quot;&gt;{2}&lt;/a&gt;!.
        /// </summary>
        internal static string MapShare {
            get {
                return ResourceManager.GetString("MapShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No maps found by provided search prompt..
        /// </summary>
        internal static string MapsNotFound {
            get {
                return ResourceManager.GetString("MapsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in browser.
        /// </summary>
        internal static string OpenBrowser {
            get {
                return ResourceManager.GetString("OpenBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open in Telegram.
        /// </summary>
        internal static string OpenWebapp {
            get {
                return ResourceManager.GetString("OpenWebapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hello, {0}.
        ///You can just write your request to this dialog, and the bot will automatically find the results for the request - maps, addresses, cadastral numbers.
        ///Also, in any dialog, you can use `@{1} (your search prompt)`, you will be given a list of maps by provided search prompt, and the ability to send any card to the current chat..
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
    }
}
